const { contextBridge, ipcRenderer } = require('electron');

// ── Canal whitelists ──
//
// Se generan desde el código fuente con `npm run ipc:channels` y se verifican
// con `npm run ipc:check`. Antes eran tres listas escritas a mano y derivaron
// en drift en las dos direcciones: canales sin handler (la UI recibía
// "No handler registered") y handlers registrados que el preload no exponía.
// ── BEGIN GENERATED CHANNELS ──
// Auto-generated by scripts/generate-ipc-channels.js — DO NOT EDIT MANUALLY

const INVOKE_CHANNELS = [
  'app:get-version',
  'check-ssh-status',
  'cloudflare:clean-aaaa',
  'cloudflare:get-zones',
  'cms:abort',
  'cms:audit-server',
  'cms:flush-permalinks',
  'cms:get-state',
  'cms:start-batch',
  'config:get',
  'config:get-cloudflare-account-id',
  'config:get-cloudflare-token',
  'config:get-github-token',
  'config:get-google-drive',
  'config:get-ssl-email',
  'config:select-drive-credentials',
  'config:set-cloudflare-account-id',
  'config:set-cloudflare-token',
  'config:set-drive-root',
  'config:set-github-token',
  'config:set-ssl-email',
  'config:validate',
  'correo:contrasena:eliminar',
  'correo:contrasena:existe',
  'correo:contrasena:guardar',
  'deployment:check-status',
  'deployment:get-processed-list',
  'deployment:run-batch',
  'dialog:open-directory',
  'dialog:open-file',
  'drive:check-auth',
  'drive:logout',
  'drive:start-auth',
  'drive:start-sync',
  'drive:stop-sync',
  'email:download-batch',
  'email:download-domain',
  'email:get-config',
  'email:restore-batch',
  'email:set-config',
  'extraction:check-status',
  'extraction:extract-ultra-lite',
  'extraction:run-batch',
  'fleet:diagnose-site',
  'fleet:get-log',
  'fleet:run-action',
  'fleet:run-deduped-batch',
  'fleet:run-mitigation',
  'fleet:scan-health',
  'get-cloudflare-status',
  'get-deployment-status',
  'get-detailed-storage',
  'get-extraction-status',
  'get-ssl-status',
  'hardening:abort',
  'hardening:get-measures',
  'hardening:run-batch',
  'hardening:run-domain',
  'hardening:unlock',
  'hardening:verify-batch',
  'hardening:verify-domain',
  'health:cancel',
  'health:check-mass',
  'health:heal-batch',
  'health:heal-domain',
  'log:get-recent',
  'logs:get-all',
  'module:clear-results',
  'module:get-status',
  'orquestador:detener',
  'php:obtener-versiones',
  'progress-get-active',
  'progress-get-history',
  'progress-get-task',
  'progress-get-tasks',
  'purge-plesk-backups',
  'reconstructor:obtener-versiones',
  'rescuesorter:cancel-massive-tar',
  'rescuesorter:diet-mode',
  'rescuesorter:extract-massive-tar',
  'rescuesorter:process',
  'scanner:finish',
  'scanner:init-pending',
  'scanner:run-audit',
  'scanner:run-clean',
  'scanner:run-harden',
  'security:credential-reset',
  'security:reboot',
  'security:shutdown',
  'security:validate-password',
  'server:check-connection',
  'server:delete',
  'server:diagnostics',
  'server:exec-command',
  'server:metrics-fetch',
  'server:metrics-start',
  'server:metrics-stop',
  'server:resolve-ip',
  'server:tail-log',
  'server:test-connection',
  'services:initialize',
  'shell:open-external',
  'sourcesync:deploy',
  'sourcesync:get-state',
  'ssh:generate-key',
  'ssh:inject-key',
  'ssh:test-connection',
  'syncdns:load-csv',
  'syncdns:run-batch',
  'utils:lookup-host',
  'uuid:generate',
  'uuid:generate-script-name',
  'uuid:generate-task-id',
  'workspace:create-account-folder',
  'workspace:create-cloud-folder',
  'workspace:create-domain-folder',
  'workspace:get-dominios-procesados',
  'workspace:get-path',
  'workspace:get-stats',
  'workspace:scan',
  'workspace:scan-domains',
  'workspace:set-path',
  'workspace:update-dominios-procesados',
];

const SEND_CHANNELS = [
  'app:frontend-ready',
  'cloudflare:sync-domains',
  'config:load',
  'config:save',
  'module:cancel',
  'module:execute',
  'plesk:install-ssl',
  'plesk:provision-domain',
  'progress:subscribe',
  'progress:unsubscribe',
  'server:maintenance',
  'updater:check-manually',
  'updater:quit-and-install',
];

const RECEIVE_CHANNELS = [
  'cloudflare:log',
  'cloudflare:state-changed',
  'cloudflare:sync-completed',
  'cloudflare:sync-error',
  'cms:audit-progress',
  'cms:progress',
  'config:loaded',
  'config:saved',
  'config:updated',
  'deployment:log',
  'deployment:state-changed',
  'domain-process-result',
  'drive:log',
  'drive:sync-complete',
  'email:log',
  'extraction:log',
  'extraction:state-changed',
  'fleet:batch-progress',
  'fleet:domain-status',
  'fleet:health-progress',
  'hardening:progress',
  'hardening:result',
  'health:heal-progress',
  'health:progress',
  'log:batch',
  'migrate-domain-error',
  'migrate-domain-start',
  'migrate-domain-success',
  'migrate-domain-warning',
  'module:completed',
  'module:error',
  'progress:update',
  'provisioning:log',
  'provisioning:state-changed',
  'provisioning:sync-error',
  'rescuesorter:progress',
  'scalify:progreso',
  'scanner:clean-progress',
  'security:credential-progress',
  'server:maintenance-completed',
  'server:metrics-update',
  'sourcesync:progreso',
  'ssl:log',
  'ssl:state-changed',
  'ssl:sync-completed',
  'ssl:sync-error',
  'state:update',
  'sync:domain-progress',
  'sync:domain-start',
  'syncdns:log',
  'syncdns:state-changed',
  'updater:checking',
  'updater:download-progress',
  'updater:error',
  'updater:not-available',
  'updater:update-available',
  'updater:update-downloaded',
  'workspace:scanned',
];
// ── END GENERATED CHANNELS ──

// ── Helper: typed invoke with whitelist validation ──
function safeInvoke(channel, data) {
  if (INVOKE_CHANNELS.includes(channel)) {
    return ipcRenderer.invoke(channel, data);
  }
  console.warn(`Attempted to invoke on invalid channel: ${channel}`);
  return Promise.reject(new Error(`Invalid channel: ${channel}`));
}

// ── Helper: safe receive with cleanup return ──
function safeReceive(channel, cb) {
  if (RECEIVE_CHANNELS.includes(channel)) {
    const handler = (_event, ...args) => cb(...args);
    ipcRenderer.on(channel, handler);
    return () => ipcRenderer.removeListener(channel, handler);
  }
  console.warn(`Attempted to receive on invalid channel: ${channel}`);
  return () => { };
}

// ── Expose legacy window.api (backward compatible) ──
contextBridge.exposeInMainWorld('api', {
  // Send methods (renderer → main)
  send: (channel, data) => {
    if (SEND_CHANNELS.includes(channel)) {
      ipcRenderer.send(channel, data);
    } else {
      console.warn(`Attempted to send on invalid channel: ${channel}`);
    }
  },

  // Receive methods (main → renderer)
  receive: (channel, func) => {
    if (RECEIVE_CHANNELS.includes(channel)) {
      // Deliberately strip event as it includes `sender`
      const handler = (event, ...args) => func(...args);
      ipcRenderer.on(channel, handler);
      return () => ipcRenderer.removeListener(channel, handler);
    } else {
      console.warn(`Attempted to receive on invalid channel: ${channel}`);
      return () => {};
    }
  },

  // Remove listener
  removeListener: (channel, func) => {
    if (RECEIVE_CHANNELS.includes(channel)) {
      ipcRenderer.removeListener(channel, func);
    } else {
      console.warn(`Attempted to remove listener from invalid channel: ${channel}`);
    }
  },

  // Remove all listeners for a channel
  removeAllListeners: (channel) => {
    if (RECEIVE_CHANNELS.includes(channel)) {
      ipcRenderer.removeAllListeners(channel);
    } else {
      console.warn(`Attempted to remove all listeners from invalid channel: ${channel}`);
    }
  },

  // Invoke methods (renderer → main → renderer with response)
  invoke: (channel, data) => {
    return safeInvoke(channel, data);
  }
});

// ── Expose typed window.electronAPI (preferred API) ──
contextBridge.exposeInMainWorld('electronAPI', {
  // ── State subscriptions ──
  /** Subscribe to full state updates from AppStateManager. Returns cleanup function. */
  onStateUpdate: (cb) => {
    return safeReceive('state:update', cb);
  },

  // ── Domain-specific queries ──
  /** Check if SSH connection is active. */
  checkSshStatus: () => {
    return safeInvoke('check-ssh-status');
  },

  /** Get current state for a specific module. */
  getModuleState: (moduleId) => {
    return safeInvoke('module:get-status', { moduleId });
  },

  /** Get full app config. */
  getConfig: () => {
    return safeInvoke('config:get');
  },

  /** Sync Cloudflare DNS records. */
  syncCloudflareDns: (params) => {
    return safeInvoke('cloudflare:sync-domains', params);
  },

  /**
   * Install bulk SSL certificates via Plesk.
   * Es un canal fire-and-forget (ipcMain.on), no un invoke: usaba safeInvoke
   * y siempre habría fallado. El progreso llega por los eventos ssl:*.
   */
  installBulkSsl: (params) => {
    if (SEND_CHANNELS.includes('plesk:install-ssl')) {
      ipcRenderer.send('plesk:install-ssl', params);
      return true;
    }
    console.warn('Canal no disponible: plesk:install-ssl');
    return false;
  },

  // ── Generic (for backward compat and untyped use) ──
  /** Get current app version. */
  getAppVersion: () => {
    return safeInvoke('app:get-version');
  },

  /** Signal main process that frontend listeners are ready. */
  notifyFrontendReady: () => {
    if (SEND_CHANNELS.includes('app:frontend-ready')) {
      ipcRenderer.send('app:frontend-ready');
    }
  },

  /** Trigger manual update check. */
  checkForUpdates: () => {
    if (SEND_CHANNELS.includes('updater:check-manually')) {
      ipcRenderer.send('updater:check-manually');
    }
  },

  /** Subscribe to any whitelisted receive channel. Returns cleanup function. */
  onEvent: (channel, cb) => {
    return safeReceive(channel, cb);
  },

  /** Generic invoke for untyped channels. */
  invoke: (channel, data) => {
    return safeInvoke(channel, data);
  }
});

// Log that preload script has loaded
console.log('Preload script loaded: window.api + window.electronAPI are available');